global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

 # - job_name: 'dockerd-exporter'
   # static_configs:
     # - targets: ['192.46.221.204:9323', '192.46.221.172:9323', '192.46.221.166:9323', '194.195.253.158:9323']


 # - job_name: 'cadvisor'
   # static_configs:
     # - targets: ['192.46.221.204:8080', '192.46.221.172:8080', '192.46.221.166:8080', '194.195.253.158:8080']

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100


  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

